---
title: "In-class_Ex03"
author: "Zou Jiaxun"
date: "Sep 9, 2024"
data-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
format:
  html:
    code-fold: true
    code-summary: "Click to view code"
---

```{r}
pacman::p_load(sf, spNetwork, tmap, tidyverse)
```

```{r}
network <- st_read(dsn="data/geospatial", 
                   layer="Punggol_St")
```

```{r}
childcare <- st_read(dsn="data/geospatial",
                     layer="Punggol_CC")
```


```{r}
plot(network)
plot(childcare,add=T,col='red',pch = 19)
```


```{r}
plot(st_geometry(network))
plot(childcare,add=T,col='red',pch = 19)
```
```{r}
tmap_mode('plot')
tm_shape(childcare) +
  tm_dots(col = 'blue') +
  tm_shape(network) +
  tm_lines() 
tmap_mode('plot')
```
```{r}
lixels <- lixelize_lines(network, 
                         700, 
                         mindist = 375)

## comfortable walking distance is 700m
```

```{r}
samples <- lines_center(lixels) 
```

```{r}
tmap_mode('view')
tm_shape(lixels) +
  tm_lines(col = 'blue') +
  tm_shape(samples) +
  tm_dots() 
tmap_mode('plot')
```
```{r}
tmap_mode('plot')
```

```{r}
densities <- nkde(network, 
                  events = childcare,
                  w = rep(1, nrow(childcare)),
                  samples = samples,
                  kernel_name = "quartic",
                  bw = 300, 
                  div= "bw", 
                  method = "simple")
```

```{r}
samples$density <- densities
lixels$density <- densities
```

```{r}
# rescaling to help the mapping
samples$density <- samples$density*1000
lixels$density <- lixels$density*1000
```

```{r}
kfun_childcare <- kfunctions(network,
                            childcare,
                            start = 0,
                            end = 1000,
                            step = 50,
                            width = 50,
                            nsim = 50,
                            resolution = 50,
                            verbose = FALSE,
                            conf_int = 0.05)
```

```{r}
kfun_childcare$plotk
```
```