---
title: "In-class_Ex10"
author: "Zou Jiaxun"
date: "Nov 4, 2024"
data-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
  cache: true
format:
  html:
    code-fold: true
    code-summary: "Click to view code"
---

```{r}
pacman::p_load(tidyverse, sf, tmap, httr, performance)
```

```{r}
realis_data <- read.csv("data/ResidentialTransaction20241110111743.csv")
condo_resale <- realis_data %>%
  mutate(`Sale.Date` = dmy(`Sale.Date`)) %>%
  filter(`Type.of.Sale` == "Resale" &
           `Property.Type` == "Condominium")
```

```{r}
postcode <- unique(condo_resale$`Postal.Code`)
```

```{r}
url <- "https://onemap.gov.sg/api/common/elastic/search"
found <- data.frame()
not_found <- data.frame()

for (postcode in postcode){
  query <- list('searchVal'=postcode, 'returnGeom'='Y', 
                'getAddrDetails'='Y', 'pageNum'='1')
  res <- GET(url, query=query)
  if ((content(res)$found)!=0){
    found <- rbind(found, data.frame(content(res))[4:13])
  } else {not_found = data.frame(postcode)
  }
}
```

```{r}
found <- found %>%
  select(c(6:8)) %>%
  rename(POSTAL = `results.POSTAL`,
         XCOORD = `results.X`,
         YCOORD = `results.Y`)
```

```{r}
condo_resale$Postal.Code <- as.character(condo_resale$Postal.Code)
result <- left_join(condo_resale, found, by = c("Postal.Code" = "POSTAL"))
```

```{r}
condo_resale_geocoded <- result %>%
  filter(!is.na(XCOORD) & !is.na(YCOORD))

condo_resale_sf <- st_as_sf(condo_resale_geocoded, 
                            coords = c("XCOORD", "YCOORD"),
                            crs = 3414)
```

```{r}
overlapping_points <- condo_resale_sf %>%
  mutate(overlap = lengths(st_equals(., .)) > 1)
```

```{r}
condo_resale_sf <- condo_resale_sf %>%
  st_jitter(amount = 2)
```


## Origin_Age Group

## 10(b) the gravity model

glm for the formualr of log transformation

## Tanzaniya

district boundary (TK3: center of the island, check it first ) sf_polygon \<- prov_sf %\>% st_cast("POLYGON") %\>% mutate(area = st_area(.))

And reback it to the same number of mutipolygon

There is no holes after the clean data map
