<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.55">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Zou Jiaxun">
<meta name="dcterms.date" content="2024-11-04">

<title>Take-home_Ex03</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../Picture/Logo2.gif" alt="" class="navbar-logo">
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exerciese" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-on Exerciese</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exerciese">    
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html">
 <span class="dropdown-text">Hands-on Exercise 1(a)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01_2.html">
 <span class="dropdown-text">Hands-on Exercise 1(b)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html">
 <span class="dropdown-text">Hands-on Exercise 2(a)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html">
 <span class="dropdown-text">Hands-on Exercise 2(b)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html">
 <span class="dropdown-text">Hands-on Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.html">
 <span class="dropdown-text">Hands-on Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05(a).html">
 <span class="dropdown-text">Hands-on Exercise 5(a)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05(b).html">
 <span class="dropdown-text">Hands-on Exercise 5(b)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html">
 <span class="dropdown-text">Hands-on Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html">
 <span class="dropdown-text">Hands-on Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html">
 <span class="dropdown-text">Hands-on Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html">
 <span class="dropdown-text">Hands-on Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html">
 <span class="dropdown-text">Hands-on Exercise 10(a)</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10(b).html">
 <span class="dropdown-text">Hands-on Exercise 10(b)</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex01/In-class_Ex01.html">
 <span class="dropdown-text">In-class Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex02/In-class_Ex02.html">
 <span class="dropdown-text">In-class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex03/In-class_Ex03.html">
 <span class="dropdown-text">In-class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex04/In-class_Ex04.html">
 <span class="dropdown-text">In-class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex05/In-class_Ex05.html">
 <span class="dropdown-text">In-class Exercise 5</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex06/In-class_Ex06.html">
 <span class="dropdown-text">In-class Exercise 6</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex07/In-class_Ex07.html">
 <span class="dropdown-text">In-class Exercise 7</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex08/In-class_Ex08.html">
 <span class="dropdown-text">In-class Exercise 8</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex09/In-class_Ex09.html">
 <span class="dropdown-text">In-class Exercise 9</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-class_Ex/In-class_Ex10/In-class_Ex10.html">
 <span class="dropdown-text">In-class Exercise 10</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-home_Ex01/Take-home_Ex01.html">
 <span class="dropdown-text">Take-home Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-home_Ex02/Take-home_Ex02.html">
 <span class="dropdown-text">Take-home Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Take-Home_Ex/Take-home_Ex03/Take-home_Ex03.html">
 <span class="dropdown-text">Take-home Exercise 3</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://twitter.com" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-twitter"></i></a>
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/Fnrion/ISSS-626">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://bugs.com">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#overview" id="toc-overview" class="nav-link active" data-scroll-target="#overview">1 Overview</a>
  <ul class="collapse">
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background">1.1 Background</a></li>
  <li><a href="#objectives" id="toc-objectives" class="nav-link" data-scroll-target="#objectives">1.2 Objectives</a></li>
  </ul></li>
  <li><a href="#data-wrangling" id="toc-data-wrangling" class="nav-link" data-scroll-target="#data-wrangling">2 Data Wrangling</a>
  <ul class="collapse">
  <li><a href="#loading-packages" id="toc-loading-packages" class="nav-link" data-scroll-target="#loading-packages">2.1 Loading Packages</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">2.2 Data Preparation</a></li>
  <li><a href="#merging-survey-and-geospatial-data" id="toc-merging-survey-and-geospatial-data" class="nav-link" data-scroll-target="#merging-survey-and-geospatial-data">Merging Survey and Geospatial Data</a></li>
  </ul></li>
  <li><a href="#geospatial-analysis-with-gwr" id="toc-geospatial-analysis-with-gwr" class="nav-link" data-scroll-target="#geospatial-analysis-with-gwr">3 Geospatial Analysis with GWR</a>
  <ul class="collapse">
  <li><a href="#exploratory-spatial-data-analysis-esda" id="toc-exploratory-spatial-data-analysis-esda" class="nav-link" data-scroll-target="#exploratory-spatial-data-analysis-esda">3.1 Exploratory Spatial Data Analysis (ESDA)</a></li>
  <li><a href="#preparing-for-geographically-weighted-regression-gwr" id="toc-preparing-for-geographically-weighted-regression-gwr" class="nav-link" data-scroll-target="#preparing-for-geographically-weighted-regression-gwr">3.2 Preparing for Geographically Weighted Regression (GWR)</a></li>
  <li><a href="#model-validation" id="toc-model-validation" class="nav-link" data-scroll-target="#model-validation">3.3 Model Validation</a></li>
  <li><a href="#interpretation-of-t-value" id="toc-interpretation-of-t-value" class="nav-link" data-scroll-target="#interpretation-of-t-value">3.4 Interpretation of T-value</a></li>
  <li><a href="#spatial-pattern-identification" id="toc-spatial-pattern-identification" class="nav-link" data-scroll-target="#spatial-pattern-identification">Spatial Pattern Identification</a></li>
  <li><a href="#future-work" id="toc-future-work" class="nav-link" data-scroll-target="#future-work">4 Future Work</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">5 Summary</a></li>
  <li><a href="#reference" id="toc-reference" class="nav-link" data-scroll-target="#reference">6 Reference</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-home_Ex03</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Zou Jiaxun </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 4, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>1 Overview</h1>
<section id="background" class="level2">
<h2 class="anchored" data-anchor-id="background">1.1 Background</h2>
<p>Financial inclusion plays a vital role in promoting economic stability and growth, especially in developing economies like Tanzania. Access to financial services empowers individuals, enabling them to save, borrow, insure, and invest, ultimately fostering resilience against economic shocks. Despite progress, challenges remain in ensuring that financial services reach all population segments, particularly those in rural and economically disadvantaged regions. Factors such as geographic location, socioeconomic status, and income sources contribute to disparities in financial access across Tanzania’s diverse regions.</p>
<p>The <strong>FinScope Tanzania 2023 survey</strong> provides comprehensive data on financial service uptake and barriers faced by Tanzanian adults. This survey offers insights into various financial services, including banking, mobile money, insurance, and microfinance, as well as informal financial mechanisms. Given Tanzania’s diverse agro-economic zones and urban-rural divide, financial inclusion determinants are expected to vary significantly by location. To capture these spatial dynamics, this study employs <strong>Geographically Weighted Regression (GWR)</strong>, a statistical technique that models spatially varying relationships between variables. By applying GWR, this analysis aims to uncover regional patterns in financial inclusion, thereby identifying localized factors influencing access to financial services across Tanzania.</p>
</section>
<section id="objectives" class="level2">
<h2 class="anchored" data-anchor-id="objectives">1.2 Objectives</h2>
<p>The main objectives of this exercise are:</p>
<ul>
<li><p><strong>To assess the spatial variability of financial inclusion</strong> across Tanzania, identifying how geographic location influences access to and usage of financial services.</p></li>
<li><p><strong>To examine relationships between financial inclusion and socio-economic variables</strong> such as income sources, urbanization level, and economic activity. This includes understanding the role of mobile money, banking, and informal financial services across different regions.</p></li>
<li><p><strong>To apply and interpret GWR in analyzing financial inclusion</strong> by generating regional coefficients that highlight spatial patterns in the data, helping to pinpoint areas where specific financial services are more or less accessible.</p></li>
<li><p><strong>To produce visualizations of GWR outputs</strong>, including maps of local coefficients and R-squared values, to clearly communicate findings on regional disparities in financial inclusion.</p></li>
</ul>
<p>By achieving these objectives, this analysis will contribute to a more nuanced understanding of financial inclusion in Tanzania, offering actionable insights for policymakers, financial service providers, and development organizations to address gaps in financial access.</p>
</section>
</section>
<section id="data-wrangling" class="level1">
<h1>2 Data Wrangling</h1>
<section id="loading-packages" class="level2">
<h2 class="anchored" data-anchor-id="loading-packages">2.1 Loading Packages</h2>
<p>To prepare and analyze spatial data for Geographically Weighted Regression (GWR), we will use the following packages, which offer tools for geospatial data handling, data manipulation, visualization, and statistical analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, spgwr, tmap, tidyverse, dplyr, </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>               ggplot2, GWmodel, readxl, knitr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>package_info <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Package =</span> <span class="fu">c</span>(</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">"sf"</span>, <span class="st">"spgwr"</span>, <span class="st">"tmap"</span>, <span class="st">"tidyverse"</span>, <span class="st">"dplyr"</span>, </span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">"ggplot2"</span>, <span class="st">"readxl"</span>, <span class="st">"knitr"</span>, <span class="st">"GWmodel"</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Description =</span> <span class="fu">c</span>(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For importing, managing, and handling geospatial data, including shapefiles and CRS transformations."</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For conducting Geographically Weighted Regression (GWR) analysis to examine spatially varying relationships."</span>,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For thematic mapping and creating visualizations to display spatial data and GWR results."</span>,</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For data wrangling and analysis, providing a cohesive set of tools for data science tasks, including ggplot2 and tidyr."</span>,</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For efficient data manipulation, including filtering, selecting, and summarizing data."</span>,</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For creating additional custom and publication-ready visualizations."</span>,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For importing Excel files, useful for reading metadata or data dictionaries."</span>,</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For dynamic report generation using LaTeX, HTML, and Markdown."</span>,</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"For conducting Geographically Weighted Regression (GWR) analysis to examing the model"</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(package_info, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Package"</span>, <span class="st">"Description"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 92%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Package</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">sf</td>
<td style="text-align: left;">For importing, managing, and handling geospatial data, including shapefiles and CRS transformations.</td>
</tr>
<tr class="even">
<td style="text-align: left;">spgwr</td>
<td style="text-align: left;">For conducting Geographically Weighted Regression (GWR) analysis to examine spatially varying relationships.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">tmap</td>
<td style="text-align: left;">For thematic mapping and creating visualizations to display spatial data and GWR results.</td>
</tr>
<tr class="even">
<td style="text-align: left;">tidyverse</td>
<td style="text-align: left;">For data wrangling and analysis, providing a cohesive set of tools for data science tasks, including ggplot2 and tidyr.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">dplyr</td>
<td style="text-align: left;">For efficient data manipulation, including filtering, selecting, and summarizing data.</td>
</tr>
<tr class="even">
<td style="text-align: left;">ggplot2</td>
<td style="text-align: left;">For creating additional custom and publication-ready visualizations.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">readxl</td>
<td style="text-align: left;">For importing Excel files, useful for reading metadata or data dictionaries.</td>
</tr>
<tr class="even">
<td style="text-align: left;">knitr</td>
<td style="text-align: left;">For dynamic report generation using LaTeX, HTML, and Markdown.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">GWmodel</td>
<td style="text-align: left;">For conducting Geographically Weighted Regression (GWR) analysis to examing the model</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">2.2 Data Preparation</h2>
<p>We will use the FinScope Tanzania 2023 data and the geoBoundaries Tanzania district shapefile for this analysis. This section includes steps to import, clean, and prepare the data for Geographically Weighted Regression.</p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true">Aspatial Data</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false">Geospatial Data</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p><strong>Survey Data</strong>: Import and clean the FinScope survey data, focusing on financial inclusion indicators, socioeconomic variables, and regional identifiers.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>survey_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data/FinScope Tanzania 2023_Individual Main Data_FINAL.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(survey_data)</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Select relevant columns for analysis</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>survey_data <span class="ot">&lt;-</span> survey_data <span class="sc">%&gt;%</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(reg_name, RU, MZ, MM, BANKED, MFI, PENSION, INSURANCE, SACCO, </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>         OTHER_FORMAL, OVERALL_FORMAL, IncomeMain, BusO, </span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>         DEDICATED_FARMER, SMALLHOLDER_FARMER, population_wt, fasx, INFORMAL)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the cleaned data</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(survey_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>       reg_name            RU       MZ     MM     BANKED     MFI     PENSION
1        Mwanza         Rural Mainland     MM Not Banked Not MFI Not PENSION
2        Kagera         Rural Mainland Not MM Not Banked Not MFI Not PENSION
3         Mbeya   Other urban Mainland     MM Not Banked Not MFI Not PENSION
4        Dodoma   Other urban Mainland     MM Not Banked Not MFI Not PENSION
5 Dar es Salaam Dar es Salaam Mainland     MM Not Banked Not MFI Not PENSION
6       Singida   Other urban Mainland     MM Not Banked Not MFI Not PENSION
  INSURANCE     SACCO OTHER_FORMAL OVERALL_FORMAL                 IncomeMain
1         0 Not SACCO OTHER_FORMAL OVERALL_FORMAL        Farmers and fishers
2         0 Not SACCO OTHER_FORMAL OVERALL_FORMAL        Farmers and fishers
3 INSURANCE Not SACCO OTHER_FORMAL OVERALL_FORMAL    Piece work/casual labor
4         0 Not SACCO OTHER_FORMAL OVERALL_FORMAL Traders - non-agricultural
5         0 Not SACCO OTHER_FORMAL OVERALL_FORMAL        Farmers and fishers
6         0 Not SACCO OTHER_FORMAL OVERALL_FORMAL    Piece work/casual labor
             BusO     DEDICATED_FARMER     SMALLHOLDER_FARMER population_wt
1             nor Not Dedicated farmer Not Smallholder farmer      3191.110
2             nor Not Dedicated farmer Not Smallholder farmer      3675.482
3             nor Not Dedicated farmer Not Smallholder farmer      2043.709
4 Business owners Not Dedicated farmer Not Smallholder farmer      4003.168
5             nor Not Dedicated farmer Not Smallholder farmer      2618.941
6             nor Not Dedicated farmer Not Smallholder farmer      4680.350
                   fasx                                       INFORMAL
1 Other formal non-bank INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS
2 Other formal non-bank INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS
3 Other formal non-bank INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS
4 Other formal non-bank INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS
5 Other formal non-bank INFORMAL incl SACCO AND CMG RISK CONTRIBUTIONS
6 Other formal non-bank                                   Not INFORMAL</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>binary_vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"BANKED"</span>, <span class="st">"MFI"</span>, <span class="st">"INSURANCE"</span>, <span class="st">"SACCO"</span>, <span class="st">"OTHER_FORMAL"</span>, <span class="st">"OVERALL_FORMAL"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>survey_data <span class="ot">&lt;-</span> survey_data <span class="sc">%&gt;%</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">BANKED =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(BANKED), <span class="dv">0</span>, <span class="fu">ifelse</span>(BANKED <span class="sc">==</span> <span class="st">"Banked"</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">MFI =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(MFI), <span class="dv">0</span>, <span class="fu">ifelse</span>(MFI <span class="sc">==</span> <span class="st">"MFI"</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">INSURANCE =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(INSURANCE), <span class="dv">0</span>, <span class="fu">ifelse</span>(INSURANCE <span class="sc">==</span> <span class="st">"INSURANCE"</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">SACCO =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(SACCO), <span class="dv">0</span>, <span class="fu">ifelse</span>(SACCO <span class="sc">==</span> <span class="st">"SACCO"</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">OTHER_FORMAL =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(OTHER_FORMAL), <span class="dv">0</span>, <span class="fu">ifelse</span>(OTHER_FORMAL <span class="sc">==</span> <span class="st">"OTHER_FORMAL"</span>, <span class="dv">1</span>, <span class="dv">0</span>)),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">OVERALL_FORMAL =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(OVERALL_FORMAL), <span class="dv">0</span>, <span class="fu">ifelse</span>(OVERALL_FORMAL <span class="sc">==</span> <span class="st">"OVERALL_FORMAL"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Check structure to verify transformations</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(survey_data[, <span class="fu">c</span>(<span class="st">"BANKED"</span>, <span class="st">"MFI"</span>, <span class="st">"INSURANCE"</span>, <span class="st">"SACCO"</span>, <span class="st">"OTHER_FORMAL"</span>, <span class="st">"OVERALL_FORMAL"</span>)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   9915 obs. of  6 variables:
 $ BANKED        : num  0 0 0 0 0 0 0 0 1 0 ...
 $ MFI           : num  0 0 0 0 0 0 0 0 0 0 ...
 $ INSURANCE     : num  0 0 1 0 0 0 0 0 0 0 ...
 $ SACCO         : num  0 0 0 0 0 0 0 0 0 0 ...
 $ OTHER_FORMAL  : num  1 1 1 1 1 1 1 1 1 1 ...
 $ OVERALL_FORMAL: num  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate proportions by region</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>region_proportions <span class="ot">&lt;-</span> survey_data <span class="sc">%&gt;%</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(reg_name) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">all_of</span>(binary_vars), <span class="sc">~</span> <span class="fu">mean</span>(<span class="fu">as.numeric</span>(.), <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.names =</span> <span class="st">"prop_{col}"</span>))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(region_proportions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 31 × 7
   reg_name     prop_BANKED prop_MFI prop_INSURANCE prop_SACCO prop_OTHER_FORMAL
   &lt;chr&gt;              &lt;dbl&gt;    &lt;dbl&gt;          &lt;dbl&gt;      &lt;dbl&gt;             &lt;dbl&gt;
 1 Arusha             0.298   0.105          0.137     0.00317             0.784
 2 Dar es Sala…       0.437   0.159          0.215     0.0142              0.943
 3 Dodoma             0.198   0.0951         0.180     0.0121              0.773
 4 Geita              0.152   0.0365         0.0590    0.00281             0.753
 5 Iringa             0.222   0.0711         0.138     0.00444             0.724
 6 Kagera             0.132   0.0140         0.0588    0.0168              0.650
 7 Kaskazini P…       0.175   0.0361         0.0567    0.00515             0.686
 8 Kaskazini U…       0.167   0.0444         0.0278    0.0278              0.806
 9 Katavi             0.211   0.0404         0.103     0.00448             0.776
10 Kigoma             0.118   0.0112         0.0848    0.00670             0.569
# ℹ 21 more rows
# ℹ 1 more variable: prop_OVERALL_FORMAL &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Save csv</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(survey_data, <span class="st">"data/csv/survey_data.csv"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write.csv</span>(region_proportions, <span class="st">"data/csv/region_proportions"</span>, <span class="at">row.names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p>We’ll use the district boundary shapefile (geoBoundaries-TZA-ADM2.shp) to perform spatial analysis. This shapefile represents Tanzania’s districts and will be joined with the survey data.</p>
<p>Since the district boundaries shapefile has <code>MULTIPOLYGON</code> geometries, we will convert them to <code>POLYGON</code> geometries to ensure compatibility with our analysis. We’ll also add a new column for the area of each polygon, which could be useful for weighting or further spatial analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load and transform the ADM1 shapefile</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>regions <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"data/ADM1/geoBoundaries-TZA-ADM1.shp"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">32737</span>)  <span class="co"># Using UTM Zone 37S for Tanzania</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `geoBoundaries-TZA-ADM1' from data source 
  `/Applications/SMU/S3/ISSS626 - Geo/ISSS-626 ZOUJIAXUN/Take-home_Ex/Take-home_Ex03/data/ADM1/geoBoundaries-TZA-ADM1.shp' 
  using driver `ESRI Shapefile'
Simple feature collection with 30 features and 5 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 29.32698 ymin: -11.76125 xmax: 40.44556 ymax: -0.9854812
Geodetic CRS:  WGS 84</code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert MULTIPOLYGON to individual POLYGON components and calculate area</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>regions_polygons <span class="ot">&lt;-</span> regions <span class="sc">%&gt;%</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_cast</span>(<span class="st">"POLYGON"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">area =</span> <span class="fu">st_area</span>(.))</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Group by `shapeName` to ensure each region is represented as a single MULTIPOLYGON</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>regions_cleaned <span class="ot">&lt;-</span> regions_polygons <span class="sc">%&gt;%</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(shapeName) <span class="sc">%&gt;%</span> </span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">geometry =</span> <span class="fu">st_union</span>(geometry), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the result by plotting</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(regions_cleaned))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="merging-survey-and-geospatial-data" class="level2">
<h2 class="anchored" data-anchor-id="merging-survey-and-geospatial-data">Merging Survey and Geospatial Data</h2>
<p>Now, with the POLYGON geometries and area calculated, we can merge this geospatial data with the survey data to create a combined dataset for the GWR analysis.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the survey data with the cleaned region shapefile using `shapeName` and `reg_name`</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> regions_cleaned <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(region_proportions, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"shapeName"</span> <span class="ot">=</span> <span class="st">"reg_name"</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Check the combined dataset</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  shapeName                  geometry   prop_BANKED        prop_MFI      
 Length:30          MULTIPOLYGON : 6   Min.   :0.1092   Min.   :0.01116  
 Class :character   POLYGON      :24   1st Qu.:0.1321   1st Qu.:0.04930  
 Mode  :character   epsg:32737   : 0   Median :0.1984   Median :0.06984  
                    +proj=utm ...: 0   Mean   :0.2015   Mean   :0.06676  
                                       3rd Qu.:0.2222   3rd Qu.:0.08000  
                                       Max.   :0.4370   Max.   :0.15854  
                                       NA's   :5        NA's   :5        
 prop_INSURANCE      prop_SACCO       prop_OTHER_FORMAL prop_OVERALL_FORMAL
 Min.   :0.02308   Min.   :0.000000   Min.   :0.5692    Min.   :0.5810     
 1st Qu.:0.07500   1st Qu.:0.004184   1st Qu.:0.6692    1st Qu.:0.6769     
 Median :0.10460   Median :0.006757   Median :0.7619    Median :0.7711     
 Mean   :0.10691   Mean   :0.012092   Mean   :0.7381    Mean   :0.7448     
 3rd Qu.:0.13380   3rd Qu.:0.014228   3rd Qu.:0.7841    3rd Qu.:0.7950     
 Max.   :0.21545   Max.   :0.059859   Max.   :0.9431    Max.   :0.9451     
 NA's   :5         NA's   :5          NA's   :5         NA's   :5          </code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(combined_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>sf [30 × 8] (S3: sf/tbl_df/tbl/data.frame)
 $ shapeName          : chr [1:30] "Arusha" "Dar es Salaam" "Dodoma" "Geita" ...
 $ geometry           :sfc_GEOMETRY of length 30; first list element: List of 1
  ..$ : num [1:208, 1:2] 322668 320915 317794 314638 313041 ...
  ..- attr(*, "class")= chr [1:3] "XY" "POLYGON" "sfg"
 $ prop_BANKED        : num [1:30] 0.298 0.437 0.198 0.152 0.222 ...
 $ prop_MFI           : num [1:30] 0.1048 0.1585 0.0951 0.0365 0.0711 ...
 $ prop_INSURANCE     : num [1:30] 0.137 0.215 0.18 0.059 0.138 ...
 $ prop_SACCO         : num [1:30] 0.00317 0.01423 0.01215 0.00281 0.00444 ...
 $ prop_OTHER_FORMAL  : num [1:30] 0.784 0.943 0.773 0.753 0.724 ...
 $ prop_OVERALL_FORMAL: num [1:30] 0.784 0.945 0.773 0.753 0.738 ...
 - attr(*, "sf_column")= chr "geometry"
 - attr(*, "agr")= Factor w/ 3 levels "constant","aggregate",..: NA NA NA NA NA NA NA
  ..- attr(*, "names")= chr [1:7] "shapeName" "prop_BANKED" "prop_MFI" "prop_INSURANCE" ...</code></pre>
</div>
</div>
<p>Remove rows with NA values in the relevant columns</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>combined_data <span class="ot">&lt;-</span> combined_data <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(prop_BANKED, prop_MFI, prop_INSURANCE, prop_SACCO)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="geospatial-analysis-with-gwr" class="level1">
<h1>3 Geospatial Analysis with GWR</h1>
<section id="exploratory-spatial-data-analysis-esda" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-spatial-data-analysis-esda">3.1 Exploratory Spatial Data Analysis (ESDA)</h2>
<p>Create choropleth maps to visualize the distribution of each financial inclusion indicator across regions.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">"plot"</span>) </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define each map individually</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>map1 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_BANKED"</span>, </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of Banked Population"</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Blues"</span>, </span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Banked Population by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>map2 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_MFI"</span>, </span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of MFI Users"</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Purples"</span>, </span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"MFI Users by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>map3 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_INSURANCE"</span>, </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of Insurance Users"</span>,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Greens"</span>, </span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Insurance Users by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>map4 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_SACCO"</span>, </span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of SACCO Users"</span>,</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Oranges"</span>, </span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"SACCO Users by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>map5 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_OTHER_FORMAL"</span>, </span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of Other Formal Financial Users"</span>,</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Reds"</span>, </span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Other Formal Financial Users by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>map6 <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_OVERALL_FORMAL"</span>, </span>
<span id="cb17-41"><a href="#cb17-41" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Proportion of Overall Formal Financial Inclusion"</span>,</span>
<span id="cb17-42"><a href="#cb17-42" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"YlGnBu"</span>, </span>
<span id="cb17-43"><a href="#cb17-43" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb17-44"><a href="#cb17-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Overall Formal Financial Inclusion by Region"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span>
<span id="cb17-45"><a href="#cb17-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-46"><a href="#cb17-46" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_arrange</span>(map1, map2, map3, map4, map5, map6, <span class="at">ncol =</span> <span class="dv">3</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Urban-Rural Divide:</strong> There is a clear disparity in financial service uptake between urban and rural regions, with urbanized areas generally showing higher access to formal financial services.</p>
<p><strong>Role of MFIs and SACCOs:</strong> In areas where formal banking is limited, microfinance institutions and SACCOs provide crucial financial services, suggesting that these institutions are integral to financial inclusion strategies in rural and semi-urban areas.</p>
<p><strong>Regional Variations in Financial Inclusion:</strong> Each indicator shows distinct spatial patterns, emphasizing that financial inclusion in Tanzania is regionally diverse. This diversity likely reflects variations in socioeconomic conditions, regional policies, and accessibility of financial infrastructure.</p>
</div>
</div>
</section>
<section id="preparing-for-geographically-weighted-regression-gwr" class="level2">
<h2 class="anchored" data-anchor-id="preparing-for-geographically-weighted-regression-gwr">3.2 Preparing for Geographically Weighted Regression (GWR)</h2>
<p>Use GWR to explore the spatial variability in financial inclusion, the prop_* columns can be used as dependent or independent variables in model.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up coordinates and calculate bandwidth</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(combined_data))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>gwr_bandwidth <span class="ot">&lt;-</span> <span class="fu">bw.gwr</span>(prop_BANKED <span class="sc">~</span> prop_MFI <span class="sc">+</span> prop_INSURANCE <span class="sc">+</span> prop_SACCO, </span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">data =</span> combined_data, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">approach =</span> <span class="st">"AICc"</span>, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">kernel =</span> <span class="st">"bisquare"</span>, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                        <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Adaptive bandwidth (number of nearest neighbours): 23 AICc value: -51.36172 
Adaptive bandwidth (number of nearest neighbours): 22 AICc value: -49.6069 
Adaptive bandwidth (number of nearest neighbours): 24 AICc value: -53.01621 
Adaptive bandwidth (number of nearest neighbours): 24 AICc value: -53.01621 </code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Run GWR model without specifying `coords`, as they are embedded in `combined_data`</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>gwr_model <span class="ot">&lt;-</span> <span class="fu">gwr.basic</span>(prop_BANKED <span class="sc">~</span> prop_MFI <span class="sc">+</span> prop_INSURANCE <span class="sc">+</span> prop_SACCO, </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> combined_data, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">bw =</span> gwr_bandwidth, </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                       <span class="at">kernel =</span> <span class="st">"bisquare"</span>, </span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">adaptive =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Check the summary of the GWR model to view the results, including coefficients, local R-squared values, and diagnostics.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gwr_model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>              Length Class  Mode
GW.arguments  11     -none- list
GW.diagnostic  8     -none- list
lm            14     lm     list
SDF           19     sf     list
timings        5     -none- list
this.call      6     -none- call
Ftests         0     -none- list</code></pre>
</div>
</div>
<p>The coefficients and local R-squared values can help to understand the spatial variation in the relationship between prop_BANKED and your predictors.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract coefficient estimates and local R-squared values</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>gwr_results <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(gwr_model<span class="sc">$</span>SDF)  <span class="co"># Convert Spatial Data Frame to regular Data Frame</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gwr_results)  <span class="co"># View first few rows to check the data structure</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Intercept  prop_MFI prop_INSURANCE prop_SACCO         y      yhat
1 0.04278466 0.8314447      0.8944337 -0.8296852 0.2984127 0.2493518
2 0.06504168 0.9134198      0.8593806 -1.1239781 0.4369919 0.3790117
3 0.02530920 0.8963779      0.9255787 -0.5375104 0.1983806 0.2708177
4 0.06879238 0.8053858      0.6608077 -0.5112866 0.1516854 0.1357466
5 0.05688544 0.7905976      0.8113619 -0.3155218 0.2222222 0.2234910
6 0.06897307 0.8129905      0.6697867 -0.5857415 0.1316527 0.1099143
      residual CV_Score Stud_residual Intercept_SE prop_MFI_SE
1  0.049060939        0    1.02617289   0.03613565   0.6639298
2  0.057980179        0    2.26262510   0.04384599   0.7471723
3 -0.072437148        0   -1.58603717   0.04089960   0.7261918
4  0.015938823        0    0.30388209   0.03802964   0.6703635
5 -0.001268799        0   -0.02606759   0.04228120   0.6839875
6  0.021738349        0    0.49758427   0.03828892   0.6707030
  prop_INSURANCE_SE prop_SACCO_SE Intercept_TV prop_MFI_TV prop_INSURANCE_TV
1         0.4882944      1.125925     1.184001    1.252308          1.831751
2         0.4937246      1.045385     1.483413    1.222502          1.740607
3         0.5130715      1.054263     0.618813    1.234354          1.803996
4         0.4851896      1.045673     1.808915    1.201416          1.361958
5         0.4702472      1.167463     1.345407    1.155865          1.725394
6         0.4877893      1.067588     1.801384    1.212147          1.373107
  prop_SACCO_TV  Local_R2                       geometry
1    -0.7368919 0.7526119 POLYGON ((322667.9 9679662,...
2    -1.0751810 0.6471317 MULTIPOLYGON (((601932.5 92...
3    -0.5098447 0.6782635 POLYGON ((91973.24 9464524,...
4    -0.4889547 0.8452564 POLYGON ((-372724.1 9626877...
5    -0.2702628 0.6426588 POLYGON ((18635.87 9041024,...
6    -0.5486589 0.8742013 POLYGON ((-196727 9888805, ...</code></pre>
</div>
</div>
<p>Use tmap or ggplot2 to visualize the spatial distribution of the coefficients and R-squared values.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ensure column names in gwr_results match expected names</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>prop_MFI_coef <span class="ot">&lt;-</span> gwr_results<span class="sc">$</span>prop_MFI</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>prop_INSURANCE_coef <span class="ot">&lt;-</span> gwr_results<span class="sc">$</span>prop_INSURANCE</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>prop_SACCO_coef <span class="ot">&lt;-</span> gwr_results<span class="sc">$</span>prop_SACCO</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>Local_R2 <span class="ot">&lt;-</span> gwr_results<span class="sc">$</span>Local_R2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Map the coefficients for each predictor</strong></p>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true">Map for prop_MFI coefficient</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false">Map for prop_INSURANCE coefficient</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false">Map for prop_SACCO coefficient</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false">Map for Local R-squared values</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_MFI_coef"</span>, </span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"GWR Coefficient for MFI Proportion"</span>,</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Spatial Variation of GWR Coefficient for MFI Proportion"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: This map shows the spatial variation in the relationship between the proportion of people using microfinance institutions (MFI) and the proportion of people who are banked.</p>
<p><strong>Observation</strong>: Regions with higher positive coefficients (blue areas) suggest that, in these areas, higher MFI participation is more strongly associated with banking inclusion. This could indicate that in these regions, microfinance institutions may serve as a stepping stone toward formal banking.</p>
<p><strong>Implication</strong>: Policymakers in these blue regions might consider strengthening connections between MFIs and traditional banks to further support financial inclusion.</p>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_INSURANCE_coef"</span>, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"GWR Coefficient for Insurance Proportion"</span>,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Spatial Variation of GWR Coefficient for Insurance Proportion"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: This map visualizes the influence of the proportion of people with insurance on the banking inclusion proportion.</p>
<p><strong>Observation</strong>: The red regions indicate areas where insurance is less strongly associated with banking inclusion, whereas the blue regions show stronger positive relationships.</p>
<p><strong>Implication</strong>: In areas where the association is weaker (red areas), it may be beneficial to examine barriers to integrating insurance with banking products. Conversely, regions with stronger associations (blue areas) could focus on promoting joint insurance and banking products to further financial inclusion.</p>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_SACCO_coef"</span>, </span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"GWR Coefficient for SACCO Proportion"</span>,</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, </span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Spatial Variation of GWR Coefficient for SACCO Proportion"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: This map indicates the relationship between the proportion of people involved in Savings and Credit Cooperative Organizations (SACCOs) and banking inclusion.</p>
<p><strong>Observation</strong>: Red regions indicate areas where SACCO participation negatively impacts banking inclusion, while lighter areas show weaker relationships. The negative values could imply that in certain regions, SACCOs might be seen as substitutes for formal banking services rather than complements.</p>
<p><strong>Implication</strong>: In areas where SACCO participation negatively impacts banking inclusion, there might be opportunities to create pathways or partnerships between SACCOs and formal banks to encourage individuals to access a broader range of financial services.</p>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"Local_R2"</span>, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">title =</span> <span class="st">"Local R-squared"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"Greens"</span>, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Local R-squared of GWR Model"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Interpretation</strong>: This map shows the local R-squared values from the GWR model, indicating how well the model explains the variability in banking inclusion in different regions.</p>
<p><strong>Observation</strong>: Regions with higher R-squared values (darker green areas) have a better model fit, suggesting that the selected independent variables explain the variation in banking inclusion well in these areas. Lower R-squared areas may require additional explanatory factors.</p>
<p><strong>Implication</strong>: For regions with lower R-squared values, further analysis could explore additional variables or factors influencing banking inclusion, as the current model might be missing local contextual factors in these areas.</p>
</div>
</div>
</div>
</section>
<section id="model-validation" class="level2">
<h2 class="anchored" data-anchor-id="model-validation">3.3 Model Validation</h2>
<p>We’ve already mapped local R-squared values, which give insight into how well the model fits in each region. Now, we can examine summary statistics or visualize these values to identify areas with stronger or weaker fits.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary of Local R-squared values</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gwr_results<span class="sc">$</span>Local_R2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.5498  0.6427  0.7015  0.7121  0.7822  0.8742 </code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of Local R-squared values</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gwr_results, <span class="fu">aes</span>(<span class="at">x =</span> Local_R2)) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">binwidth =</span> <span class="fl">0.05</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribution of Local R-squared Values"</span>, <span class="at">x =</span> <span class="st">"Local R-squared"</span>, <span class="at">y =</span> <span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Mean Local R-squared:</strong> 0.712, indicating that on average, the model explains about 71.2% of the variance in financial inclusion factors at the local level.</p>
<p><strong>Median Local R-squared:</strong> 0.7015, with the first and third quartiles at 0.6427 and 0.7822, respectively. This indicates that half of the regions have a Local R-squared between approximately 0.64 and 0.78.</p>
</div>
</div>
<p>Residuals analysis from the GWR model can help assess where the model may underestimate or overestimate banking inclusion. Mapping residuals provides insight into potential spatial patterns in model misfit.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Residual summary</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(gwr_results<span class="sc">$</span>residual)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     Min.   1st Qu.    Median      Mean   3rd Qu.      Max. 
-0.072437 -0.012753  0.004912  0.007246  0.021738  0.119104 </code></pre>
</div>
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding residuals to combined_data for mapping</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>combined_data<span class="sc">$</span>residual <span class="ot">&lt;-</span> gwr_results<span class="sc">$</span>residual</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Map residuals</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"residual"</span>, <span class="at">title =</span> <span class="st">"GWR Model Residuals"</span>, <span class="at">palette =</span> <span class="st">"RdBu"</span>, <span class="at">style =</span> <span class="st">"quantile"</span>) <span class="sc">+</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Spatial Distribution of GWR Residuals"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Red-shaded regions</strong>: These are areas where the GWR model’s predictions are higher than observed values, indicating potential overestimation. This may suggest that the model attributes higher financial inclusion here than what exists, possibly due to a lack of local adjustment in these areas.</p>
<p><strong>Blue-shaded regions</strong>: These areas have positive residuals, meaning the GWR model underestimates financial inclusion here. This underestimation may indicate unobserved local factors that enhance financial inclusion more than expected by the model’s structure.</p>
</div>
</div>
</section>
<section id="interpretation-of-t-value" class="level2">
<h2 class="anchored" data-anchor-id="interpretation-of-t-value">3.4 Interpretation of T-value</h2>
<p>We’ll look at the statistical significance of the coefficients for each predictor variable (prop_MFI, prop_INSURANCE, prop_SACCO) to understand where each factor has the strongest or weakest effect on banking inclusion.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if T-values for each coefficient exist in gwr_results and add them to combined_data</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>t_value_columns <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"prop_MFI_TV"</span>, <span class="st">"prop_INSURANCE_TV"</span>, <span class="st">"prop_SACCO_TV"</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop through each T-value column and add to combined_data if it exists in gwr_results</span></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (col_name <span class="cf">in</span> t_value_columns) {</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (col_name <span class="sc">%in%</span> <span class="fu">colnames</span>(gwr_results)) {</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>    combined_data[[col_name]] <span class="ot">&lt;-</span> gwr_results[[col_name]]</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  } <span class="cf">else</span> {</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">warning</span>(<span class="fu">paste</span>(<span class="st">"The column"</span>, col_name, <span class="st">"does not exist in gwr_results"</span>))</span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true">T-values for prop_MFI</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false">T-values for prop_INSURANCE</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false">T-values for prop_SACCO</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_MFI_TV"</span>, <span class="at">title =</span> <span class="st">"T-value for MFI Proportion"</span>, </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> t_value_breaks) <span class="sc">+</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Statistical Significance of MFI Coefficient"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>This map shows the significance of the MFI coefficient, with areas where the relationship is statistically significant highlighted in darker colors.</p></li>
<li><p>Regions in light colors may indicate non-significant relationships, where MFI involvement has a negligible effect on financial inclusion.</p></li>
</ul>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_INSURANCE_TV"</span>, <span class="at">title =</span> <span class="st">"T-value for Insurance Proportion"</span>, </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> t_value_breaks) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Statistical Significance of Insurance Coefficient"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The T-value map for insurance displays the statistical significance of the relationship between insurance coverage and financial inclusion.</p></li>
<li><p>Areas in darker shades indicate statistically significant relationships, while lighter shades show regions where the effect of insurance on financial inclusion is not significant.</p></li>
</ul>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">tm_shape</span>(combined_data) <span class="sc">+</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="st">"prop_SACCO_TV"</span>, <span class="at">title =</span> <span class="st">"T-value for SACCO Proportion"</span>, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">palette =</span> <span class="st">"RdBu"</span>, <span class="at">style =</span> <span class="st">"fixed"</span>, <span class="at">breaks =</span> t_value_breaks) <span class="sc">+</span></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Statistical Significance of SACCO Coefficient"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-home_Ex03_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>The SACCO T-value map similarly highlights the significance of the SACCO coefficient across regions.</p></li>
<li><p>Blue areas indicate statistically significant positive relationships, showing where SACCO membership contributes more strongly to financial inclusion.</p></li>
</ul>
</div>
</div>
</div>
</section>
<section id="spatial-pattern-identification" class="level2">
<h2 class="anchored" data-anchor-id="spatial-pattern-identification">Spatial Pattern Identification</h2>
<p>Using Moran’s I statistic or other spatial autocorrelation tests on the residuals can help determine if there are spatial patterns in the model errors, suggesting additional factors that might need to be incorporated.</p>
<div class="cell">
<details class="code-fold">
<summary>Click to view code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create spatial weights matrix</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>coords <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(<span class="fu">st_centroid</span>(combined_data))</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>nb <span class="ot">&lt;-</span> <span class="fu">knn2nb</span>(<span class="fu">knearneigh</span>(coords, <span class="at">k =</span> <span class="dv">4</span>)) <span class="co"># Adjust k as necessary</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>listw <span class="ot">&lt;-</span> <span class="fu">nb2listw</span>(nb, <span class="at">style =</span> <span class="st">"W"</span>)</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Moran's I for residuals</span></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>moran_test <span class="ot">&lt;-</span> <span class="fu">moran.test</span>(combined_data<span class="sc">$</span>residual, listw)</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>moran_test</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Moran I test under randomisation

data:  combined_data$residual  
weights: listw    

Moran I statistic standard deviate = 1.11, p-value = 0.1335
alternative hypothesis: greater
sample estimates:
Moran I statistic       Expectation          Variance 
       0.08998035       -0.04166667        0.01406662 </code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>With a p-value of 0.1335, the test does not show statistically significant spatial autocorrelation in the residuals. This suggests that the GWR model has effectively accounted for spatial dependence in the data, leaving minimal spatial structure in the residuals. In other words, the spatial variation in financial inclusion has been reasonably well captured by the GWR model.</p>
</div>
</div>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">4 Future Work</h2>
<p>While this analysis provides valuable insights into the spatial variability of financial inclusion in Tanzania, several additional steps could enhance the depth and utility of the findings:</p>
<ul>
<li><p><strong>Refinement of Variable Selection</strong>: Future work could include refining the independent variables used in the Geographically Weighted Regression (GWR) model by incorporating additional socio-economic, demographic, and infrastructure-related factors. For instance, variables like literacy rates, proximity to financial institutions, mobile network coverage, and GDP per capita might improve the model’s explanatory power.</p></li>
<li><p><strong>Multi-Scale Geographically Weighted Regression (MGWR)</strong>: Applying a Multi-Scale GWR (MGWR) could capture relationships at multiple spatial scales, allowing us to see how local versus regional dynamics affect financial inclusion. This model extension would be particularly useful in differentiating between local drivers (such as SACCO usage) and more widespread influences (like mobile money penetration).</p></li>
<li><p><strong>Temporal Analysis</strong>: A longitudinal study incorporating data from previous years would provide insights into how financial inclusion patterns evolve over time. This could reveal trends and help identify the impact of past policy changes or initiatives aimed at promoting financial access.</p></li>
<li><p><strong>Community-Level Analysis</strong>: Moving beyond district-level data to analyze community or ward-level patterns could provide a more granular view of financial inclusion disparities, especially in rural areas where financial service access may vary significantly within districts.</p></li>
<li><p><strong>Advanced Visualization Techniques</strong>: Leveraging interactive mapping tools or dashboards could make the findings more accessible to policymakers and stakeholders, facilitating a better understanding of spatial patterns in financial inclusion and aiding in decision-making processes.</p></li>
</ul>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">5 Summary</h2>
<p>This study explored the spatial distribution and determinants of financial inclusion across Tanzania using Geographically Weighted Regression (GWR). The ESDA maps highlighted significant regional disparities in access to financial services, with higher banking and insurance access in urban areas and greater reliance on MFIs and SACCOs in rural regions. The GWR analysis provided spatially varying coefficients, revealing how local factors affect financial inclusion differently across regions.</p>
<p>Key findings indicate an urban-rural divide, with formal banking concentrated in urbanized regions while MFIs and SACCOs serve as crucial financial channels in more remote areas. Additionally, regional variations in the influence of variables like insurance and SACCO participation suggest that local socio-economic conditions play a significant role in shaping financial access.</p>
<p>Further work could enhance this analysis by incorporating more variables, testing spatial lag models, and applying Multi-Scale GWR to capture dynamics at various spatial scales. Conducting temporal studies, assessing policy impacts, and exploring finer spatial resolutions would deepen our understanding of financial inclusion patterns, informing targeted interventions to promote inclusive financial access across Tanzania.</p>
</section>
<section id="reference" class="level2">
<h2 class="anchored" data-anchor-id="reference">6 Reference</h2>
<ul>
<li><p>Wikipedia contributors. (2023, November 10). <strong>Financial inclusion</strong>. Wikipedia, The Free Encyclopedia. Retrieved from <a href="https://en.wikipedia.org/wiki/Financial_inclusion" class="uri">https://en.wikipedia.org/wiki/Financial_inclusion</a></p></li>
<li><p>Kaliba, Aloyce R ; Bishagazi, Kaihula P ; Gongwe, Anne G (2023)&nbsp;<strong>“Financial Inclusion in Tanzania Determinants, Barriers, and Impact”</strong>,&nbsp;<em>The Journal of developing areas</em>, Vol.57 (2), pp.65-87. SMU library e-journal.</p></li>
<li><p>Jana S. Hamdan, Katharina Lehmann-Uschner &amp; Lukas Menkhoff (2022)&nbsp;<strong>Mobile Money, Financial Inclusion, and Unmet Opportunities: Evidence from Uganda</strong>, The Journal of Development Studies, 58:4, 671-691. SMU library e-journal.</p></li>
<li><p>Nguyen, Nhan Thien, et. al.&nbsp;(2021)&nbsp;<strong>“The convergence of financial inclusion across provinces in Vietnam: A novel approach”</strong>&nbsp;<em>PloS one</em>, Vol.16 (8). SMU library e-journal.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>