---
title: "In-class_Ex04"
author: "Zou Jiaxun"
date: "Sep 16, 2024"
data-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
format:
  html:
    code-fold: true
    code-summary: "Click to view code"
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse, knitr, GWmodel, ggstatsplot)
```

```{r}
hunan_sf <- st_read(dsn = "data/geospatial",
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_join <- left_join(hunan_sf, hunan2012)%>%
  select(1:3, 7, 9, 15, 16, 31, 32)
```

```{r}
hunan_sp <- hunan_join %>%
  as_Spatial()
```

```{r}
bw_CV <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
bw_AIC <- bw.gwr(GDPPC ~ 1,
                data = hunan_sp,
                approach = "CV",
                adaptive = TRUE,
                kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat <- gwss(vars = "GDPPC",
               data = hunan_sp,
               bw = bw_AIC,
               adaptive = TRUE,
               kernel = "bisquare",
                longlat = T)
```

```{r}
gwstat_df <- as.data.frame(gwstat$SDF)
```
